workflows:
  default_workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build for iOS (release)
        script: |
          flutter build ipa --release --no-codesign

      - name: Build for Android (release)
        script: |
          flutter build apk --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - omardiazburggs599@gmail.com
